// This file is automatically generated by the export-package plugin. Do not edit it manually.
export const MajorVersion = 1;
export const MinorVersion = 0;
export const PatchVersion = 19877;
export const VersionNumber = `${MajorVersion}.${MinorVersion}.${PatchVersion}`;
